version: "3.8"

services:
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:${TRAEFIK_WEB_PORT}"
      - "--log.level=INFO"
    ports:
      - "${TRAEFIK_WEB_PORT}:${TRAEFIK_WEB_PORT}"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - quest-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "quest-backend"
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ORIGIN}
      - QUEST_KEYWORD=${QUEST_KEYWORD}
    volumes:
      - ./conf/words.txt:/app/words.txt:ro
    networks:
      - quest-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_FQDN}`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.backend.middlewares=api-ratelimit"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.average=40"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.burst=20"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "quest-frontend"
    networks:
      - quest-net
    volumes:
      - ./conf/config.js:/usr/share/nginx/html/config.js:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_FQDN}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"

networks:
  quest-net:
    driver: bridge
